feat(DI): Dependency Injection tool
Aryevang/cuisine pull request #6
Opened 2021-05-08 01:44 UTC by Aryevang

This helper will hold the  instance of a registered class and then provide the same instance where is required.

2021-05-08 02:37 UTC, reynoldmorel requested changes

2021-05-08 02:37 UTC, reynoldmorel commented on src/cuisine.DI/DIHelper.cs
> +	public class DIHelper
It would be good to make this class a singleton class. Also I think the name should change. We can call it `Pool` or `InstancePool` maybe.

2021-05-08 02:37 UTC, reynoldmorel commented on src/cuisine.DI/DIHelper.cs
> +		private Dictionary<Type,Descriptor> _implenetationCollection = new Dictionary<Type, Descriptor>();
Hmmm I'm not sure if you want to have `Type` as key. Maybe if you would like to have multiple instances of a class that are being extended from other classes, I think this would fail, why not adding a simple `string` as key? You could let the developer to name it and he should ensure unique names for these instances.

2021-05-08 02:37 UTC, reynoldmorel commented on src/cuisine.DI/DIHelper.cs
> +			_implenetationCollection.TryGetValue(typeof(TClass), out descriptor);
Nice check!

2021-05-08 02:37 UTC, reynoldmorel commented on src/cuisine.DI/Descriptor.cs
> +			type = implemention.GetType();
We can add a string field `id` as mentioned above, to recognize each instance

2021-05-09 03:32 UTC, Aryevang commented on src/cuisine.DI/InstancePool.cs
> +			{
Exceptions will be managed in a higher level. In this `if` block, the key/instance will be registered only when the key is not contained in collection. That is the main reason this method is returning a `false` by default.

2021-05-09 10:37 UTC, reynoldmorel approved these changes

2021-05-09 10:37 UTC, reynoldmorel commented on src/cuisine.DI/InstancePool.cs
> +			{
Got it!

2021-05-09 10:40 UTC, reynoldmorel approved these changes

2021-05-09 10:40 UTC, reynoldmorel commented on src/cuisine.DI/InstancePool.cs
> +			string defaultKeyName = string.IsNullOrEmpty(key) == false ? key : nameof(implementation);
Nit: I think this may become a function, since it's used above too

2021-05-11 01:58 UTC, Aryevang commented on src/cuisine.DI/InstancePool.cs
> +		{
Done.

2021-05-11 02:04 UTC, merged